### ISSUE TITLE
How to use Plugin's methods

### ISSUE THREAD

**Issue by Noe-Imeji** [rosspi/gridstrap.js#12]
Hello,

I recently discovered your plugin and I like it, however after initializing the grid, I don't understand how to use Plugin's methods. What should I do to use them ?

This is an example of my code : 
`var grid = $("#grid").gridstrap();`
`var cells = grid.getCells();`

Thank you in advance for your help, and sorry for my bad english !

**Comment by rosspi** [comment]
`$("#grid").gridstrap();
var grid = $('#grid').data('gridstrap');
var cells = grid.getCells();`
